#
# lib_test application Makefile
#

# Program name
PROGRAM = lib_test

# Source files
OBJS = main.o test_csr.o test_string.o test_malloc.o

# Include common build rules
include ../common/Makefile.common
